services:
  ruby-playground:
    image: 'kelvinchin1207/ruby-playground:latest'
    restart: 'unless-stopped'
    volumes:
      - vscode:/root/.vscode
      - vscode-server:/root/.vscode-server
      - playground-data:/home/playground
    environment:
      - FEATURE_RESET=1
    hostname: ruby-playground

volumes:
  vscode:
  vscode-server:
  playground-data:
